[project]
name = "sleepy-rework-types"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["pydantic>=2.11.5"]

[project.optional-dependencies]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
